### PR TITLE
Don't install examples

### PR DESCRIPTION
**Pull request by CyberTailor**
See Gentoo Bugzilla: https://bugs.gentoo.org/835475

### CODE REVIEW

**Comment by mgorny** [comment]
I think the author meant to include them in sdist. Poetry has some awful syntax for that, something like:

```
packages = {
  ...,
  { include = "examples/*", format = "sdist" },
}
```

and so on. LICENSE and README can be omitted as they're picked up by the default rules.

**Comment by NicklasTegner** [comment]
hi @CyberTailor  thanks for the contributions.

Indeed as @mgorny  pointed out, it was expected behavior to include the examples.

Please let me know what issue you are having, as I couldn't find enough information from the link you provided :)

**Comment by CyberTailor** [comment]
> Indeed as @mgorny pointed out, it was expected behavior to include the examples.

MANIFEST.in already does that.

> Please let me know what issue you are having

See build log of linked bug:

```
 * ERROR: dev-python/pypandoc-1.7.2::guru failed (install phase):
 *   Package installs 'examples' package which is forbidden and likely a bug in the build system.
```

**Comment by NicklasTegner** [comment]
Ohh okay. I see @CyberTailor 
Would would be a prefered solution?
Removing the examples out right, or doing what @mgorny  suggested and only include them in sdist?

**Comment by sthagen** [comment]
I cannot imagine any distribution removing examples from a source package - suggest to follow the route proposed by @mgorny

**Comment by NicklasTegner** [comment]
@sthagen  maybe I'm just misreading it. But what are you suggesting?

**Comment by mgorny** [comment]
> I cannot imagine any distribution removing examples from a source package - suggest to follow the route proposed by @mgorny

For the record, I think many Python projects nowadays assume that sdists are only to be consumed by pip (or pip-alike package managers) and should contain only files strictly needed to install the package in a venv, often skipping docs, examples and tests to reduce sdist size. Not that I liked it but at this point I'm pretty much assuming sdists are incomplete and going straight for git snapshots when packaging anything for Gentoo.

**Comment by sthagen** [comment]
@NicklasTegner I referred to the proposal of @mgorny: 
> I think the author meant to include them in sdist. Poetry has some awful syntax for that, something like:
> 
> ```
> packages = {
>   ...,
>   { include = "examples/*", format = "sdist" },
> }
> ```
> 
> and so on. LICENSE and README can be omitted as they're picked up by the default rules.

That would mean add stanzas like the following in the `pyproject.toml` file:
```
 { include = "examples/*", format = "sdist" },
 { include = "tests/*", format = "sdist" },
```

Otherwise, I also gave up on `sdist` packages like @mgorny stated always hunting for the source repository to execute tests and learn from examples.

**Pull request closed without merging**
